### ISSUE TITLE
CSS Reset(초기화)

### ISSUE THREAD

**Issue by Hyeon-moGu** [Hyeon-moGu/Study-repo#15]
### CSS Reset(초기화) 이유
* 각 브라우저마다 설정되어있는 기본 스타일이 다르기 때문에
* 크로스브라우징을 위하여. 브라우저마다 HTML 시맨틱 태그에 대한 기본값이 다르므로 그 차이를 없애는 데 필요

```CSS
/* Reset.CSS */
a,abbr,acronym,address,applet,article,aside,audio,b,big,blockquote,body,canvas,caption,center,cite,code,dd,del,details,dfn,
div,dl,dt,em,embed,fieldset,figcaption,figure,footer,form,h1,h2,h3,h4,h5,h6,header,hgroup,html,i,iframe,img,ins,kbd,label,
legend,li,main,mark,menu,nav,object,ol,output,p,pre,q,ruby,s,samp,section,small,span,strike,strong,sub,summary,sup,
table,tbody,td,tfoot,th,thead,time,tr,tt,u,ul,var,video {
margin:0;
padding:0;
border:0;
font-size:100%;
font:inherit;
vertical-align:baseline }

article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section {
display:block }

[hidden] {
display:none }

body {
line-height:1 }

menu,ol,ul {
list-style:none }

blockquote,q {
quotes:none }

blockquote:after,blockquote:before,q:after,q:before {
content:'';content:none }

table { 
border-collapse:collapse;border-spacing:0 }
```
